"""init

Revision ID: 89108db743ed
Revises: ce6d745d5fdc
Create Date: 2023-12-10 14:51:38.978162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89108db743ed'
down_revision: Union[str, None] = 'ce6d745d5fdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classroom_subject_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_subject_table',
    sa.Column('classroom_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], name='classroom_subject_table_classroom_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name='classroom_subject_table_subject_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='classroom_subject_table_user_id_fkey', ondelete='CASCADE')
    )
    # ### end Alembic commands ###
