"""init

Revision ID: 94ed14376e78
Revises: 814f89396159
Create Date: 2023-12-10 20:45:35.217280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ed14376e78'
down_revision: Union[str, None] = '814f89396159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('classroom_name_key', 'classroom', type_='unique')
    op.create_unique_constraint(None, 'curriculum', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'curriculum', type_='unique')
    op.create_unique_constraint('classroom_name_key', 'classroom', ['name'])
    # ### end Alembic commands ###
