"""init

Revision ID: 9e6e9c94aade
Revises: 8c4752beb83a
Create Date: 2023-12-09 23:51:23.566942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e6e9c94aade'
down_revision: Union[str, None] = '8c4752beb83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subject_classroom_id_fkey', 'subject', type_='foreignkey')
    op.drop_column('subject', 'classroom_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('classroom_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('subject_classroom_id_fkey', 'subject', 'subject', ['classroom_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
