# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1114, 819)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(255)
        sizePolicy.setVerticalStretch(255)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1111, 771))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(255)
        sizePolicy.setVerticalStretch(255)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabTeachers = QtWidgets.QWidget()
        self.tabTeachers.setObjectName("tabTeachers")
        self.tabWidget.addTab(self.tabTeachers, "")
        self.tabSubjects = QtWidgets.QWidget()
        self.tabSubjects.setObjectName("tabSubjects")
        self.tabWidget.addTab(self.tabSubjects, "")
        self.tabStudents = QtWidgets.QWidget()
        self.tabStudents.setObjectName("tabStudents")
        self.tabWidget.addTab(self.tabStudents, "")
        self.tabAuditorium = QtWidgets.QWidget()
        self.tabAuditorium.setObjectName("tabAuditorium")
        self.tabWidget.addTab(self.tabAuditorium, "")
        self.tabSpec = QtWidgets.QWidget()
        self.tabSpec.setObjectName("tabSpec")
        self.tabWidget.addTab(self.tabSpec, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1114, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTeachers), _translate("MainWindow", "Преподаватели"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSubjects), _translate("MainWindow", "Предметы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStudents), _translate("MainWindow", "Студенты"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAuditorium), _translate("MainWindow", "Аудитории"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpec), _translate("MainWindow", "Специальности"))
